# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [4]:
arr.size * arr.itemsize

80

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
arr2 = np.zeros(10)
arr2[4] = 1  # since 5th value
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr3 = np.arange(10, 50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [8]:
arr3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr4 = np.arange(0, 9) 
arr4.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(arr)[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [23]:
np.random.random((3, 3, 3))

array([[[0.09945101, 0.88892808, 0.30236076],
        [0.61874557, 0.03837176, 0.1621723 ],
        [0.57524056, 0.59663593, 0.10535043]],

       [[0.9297111 , 0.14599987, 0.60143917],
        [0.71243063, 0.240249  , 0.74178846],
        [0.30726549, 0.51383078, 0.81798237]],

       [[0.45846511, 0.14931711, 0.33152863],
        [0.79660228, 0.50824426, 0.73986511],
        [0.92547486, 0.93973218, 0.29138207]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.random.random((10, 10))
print(arr.min())
print(arr.max())

0.013670758325668775
0.9948630925815235


#### 14. Create a random vector of size 30 and find the mean value

In [27]:
np.random.random(30).mean()

0.5950227349236209

#### 15. Create a 2d array with 1 on the border and 0 inside

In [31]:
arr = np.ones((4, 4))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [34]:
arr = np.ones((2, 2))
np.pad(arr, pad_width=1, constant_values = 0)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [41]:
0.3 == 3 * 0.1

False

In [36]:
0 * np.nan

nan

In [40]:
np.nan in set([np.nan])

True

In [39]:
np.nan - np.nan

nan

In [38]:
np.inf > np.nan

False

In [37]:
np.nan == np.nan

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [43]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [47]:
arr = np.zeros ((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [1]:
!git --version

git version 2.29.2.windows.2
